services:
  aws-exporter:
    build: .
    # environment:
    #   AWS_REGION: ${AWS_REGION}
    #   AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    #   AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    #   AWS_BUCKETS: srv-buenonetworks
    #   AWS_SCRAPE_INTERVAL: 4
    command: "--config /etc/aws-s3-exporter/config.yaml"
    volumes:
      - ./configs/config.yaml:/etc/aws-s3-exporter/config.yaml:ro
      - ~/.aws:/root/.aws:ro
    ports:
      - "2112:2112"
    networks:
      - exporter

networks:
  exporter:
    driver: bridge
