# AWS S3 Exporter Configuration
# =============================
# Este arquivo permite configurar múltiplas contas/perfis AWS para monitoramento de buckets S3.
#
# Cada item em 'aws:' representa uma conta ou perfil AWS diferente, com seus próprios buckets e intervalo de coleta.
#
# Exemplo de configuração:
#
# aws:
#   - profile: meu-profile
#     region: us-east-1
#     scrape_interval: 10 # default 5 minutos
#     buckets:
#       - meu-bucket-1
#       - meu-bucket-2
#   - profile: outro-profile
#     region: sa-east-1
#     buckets:
#       - outro-bucket

aws:
  - profile: ""
    region: ""
    scrape_interval: 10
    buckets: []
